steps:
  - id  : Build Container
    name: 'google/cloud-sdk'
    args: [
      'gcloud', 'builds', 'submit',
      '--pack', 'image=${_ARTIFACT_REGISTRY}/${_APP_NAME}:${SHORT_SHA}'
    ]

  - id  : Deploy to Cloud Run
    name: 'google/cloud-sdk'
    args: [
      'gcloud', 'run', 'deploy', '${_APP_NAME}',
      '--image', '${_ARTIFACT_REGISTRY}/${_APP_NAME}:${SHORT_SHA}',
      '--region', '${_REGION}', '--platform', 'managed',
      '--set-cloudsql-instances', '${PROJECT_ID}:${_REGION}:${_INSTANCE_NAME}',
      '--set-secrets', '/config/.env=laravel_settings:latest',
      '--allow-unauthenticated'
    ]

substitutions:
  _APP_NAME: laravel
  _INSTANCE_NAME: emagang-pgsql
  _REGION: us-central1
  _ARTIFACT_REGISTRY: ${_REGION}-docker.pkg.dev/${PROJECT_ID}/emagang-repo

