steps:
  # Docker Submit
  - id  : 'Docker Submit'
    name: 'google/cloud-sdk'
    args: ['gcloud', 'builds', 'submit',
           '--pack', 'image=${_REGISTRY_NAME}/${_APP_NAME}']

  # Docker Create
  - id  : 'Docker Create'
    name: 'google/cloud-sdk'
    args: ['gcloud', 'beta', 'run', 'jobs', 'create', 'migrate',
          '--image', '${REGISTRY_NAME}/laravel',
          '--region', '${REGION}',
          '--set-cloudsql-instances', '${PROJECT_ID}:${_REGION}:${_INSTANCE_NAME}',
          '--set-secrets', '/config/.env=laravel_settings:latest',
          '--command, launcher',
          '--args', "php artisan migrate"]

  # Docker Execute
  - id  : 'Docker Excecute'
    name: 'google/cloud-sdk'
    args: ['gcloud', 'beta', 'run', 'jobs', 'execute', 'migrate', '--region', '${REGION}', '--wait']

  # Docker Run
  - id  : 'Docker Run'
    name: 'google/cloud-sdk'
    args: ['gcloud', 'run', 'deploy', '${_APP_NAME}',
           '--image', '${_REGISTRY_NAME}/${_APP_NAME}',
           '--region', '${_ZONE_ID}', '--platform', 'managed',
           '--set-cloudsql-instances', '${PROJECT_ID}:${_REGION}:${_INSTANCE_NAME}',
           '--set-secrets', '/config/.env=laravel_settings:latest',
           '--allow-unauthenticated']

# Store images in Google Artifact Registry
images:
  - ${_REGISTRY_NAME}/${_APP_NAME}

substitutions:
  _REGISTRY_NAME: ${_REGION}-docker.pkg.dev/${PROJECT_ID}/emagang-repo
  _APP_NAME: laravel:${SHORT_SHA}
  _REGION: us-central1
  _INSTANCE_NAME: emagang-pgsql

