steps:
  - id  : Build Container
    name: 'google/cloud-sdk'
    args: [
      'gcloud', 'builds', 'submit',
      '--pack', 'image=${_ARTIFACT_REGISTRY}/${_APP_NAME}:${SHORT_SHA}'
    ]

  - id  : Create Migration
    name: 'google/cloud-sdk'
    args: [
      'gcloud', 'beta', 'run', 'jobs', 'create', 'migrate',
      '--image', '${_ARTIFACT_REGISTRY}/${_APP_NAME}:${SHORT_SHA}',
      '--region', '${_REGION}',
      '--set-cloudsql-instances', '${PROJECT_ID}:${_REGION}:${_INSTANCE_NAME}',
      '--set-secrets', '/config/.env=${_SETTING_NAME}:latest',
      '--command', 'launcher',
      '--args', '"php artisan migrate"'
    ]

  - id  : Excecute Migration
    name: 'google/cloud-sdk'
    args: [
      'gcloud', 'beta', 'run', 'execute', 'migrate', '--region', '${_REGION}', '--wait'
    ]

  - id  : Deploy to Cloud Run
    name: 'google/cloud-sdk'
    args: [
      'gcloud', 'run', 'deploy', '${_APP_NAME}',
      '--image', '${_ARTIFACT_REGISTRY}/${_APP_NAME}:${SHORT_SHA}',
      '--region', '${_REGION}', '--platform', 'managed',
      '--set-cloudsql-instances', '${PROJECT_ID}:${_REGION}:${_INSTANCE_NAME}',
      '--set-secrets', '/config/.env=${_SETTING_NAME}:latest',
      '--allow-unauthenticated'
    ]

substitutions:
  _APP_NAME: laravel
  _INSTANCE_NAME: emagang-pgsql
  _REGION: us-central1
  _SETTING_NAME: laravel_settings
  _ARTIFACT_REGISTRY: ${_REGION}-docker.pkg.dev/${PROJECT_ID}/emagang-repo

