steps:
  # Docker Submit
  - id  : 'Docker Submit'
    name: 'google/cloud-sdk'
    args: ['gcloud', 'builds', 'push', '${_ARTIFACT_REGISTRY}/${_APP_NAME}:${SHORT_SHA}']

#  # Docker Create
#  - id  : 'Docker Create'
#    name: 'google/cloud-sdk'
#    args: ['gcloud', 'beta', 'run', 'jobs', 'create', 'migrate',
#          '--image', '${_ARTIFACT_REGISTRY}/${_APP_NAME}:${SHORT_SHA}',
#          '--region', '${_REGION}',
#          '--set-cloudsql-instances', '${PROJECT_ID}:${_REGION}:${_INSTANCE_NAME}',
#          '--set-secrets', '/config/.env=laravel_settings:latest',
#          '--command', 'launcher',
#          '--args', '"php artisan migrate"']
#
#  # Docker Execute
#  - id  : 'Docker Excecute'
#    name: 'google/cloud-sdk'
#    args: ['gcloud', 'beta', 'run', 'jobs', 'execute', 'migrate', '--region', '${_REGION}', '--wait']

  # Docker Run
  - id  : 'Docker Run'
    name: 'google/cloud-sdk'
    args: ['gcloud', 'run', 'deploy', '${_APP_NAME}',
           '--image', '${_ARTIFACT_REGISTRY}/${_APP_NAME}:${SHORT_SHA}',
           '--region', '${_REGION}', '--platform', 'managed',
           '--set-cloudsql-instances', '${PROJECT_ID}:${_REGION}:${_INSTANCE_NAME}',
           '--set-secrets', '/config/.env=laravel_settings:latest',
           '--allow-unauthenticated']

# Store images in Google Artifact Registry
images:
  - ${_ARTIFACT_REGISTRY}/${_APP_NAME}:${SHORT_SHA}

substitutions:
  _APP_NAME: laravel
  _INSTANCE_NAME: emagang-pgsql
  _REGION: us-central1
  _ARTIFACT_REGISTRY: ${_REGION}-docker.pkg.dev/${PROJECT_ID}/emagang-repo

