steps:
  # Docker Build
  - id  : 'Docker Build'
    name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t',
           '${_ZONE_ID}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/${_APP_NAME}:${SHORT_SHA}', '.']

  # Docker push to Google Artifact Registry
  - id  : 'Docker push to Google Artifact Registry'
    name: 'gcr.io/cloud-builders/docker'
    args: ['push',  '${_ZONE_ID}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/${_APP_NAME}:${SHORT_SHA}']

  # Deploy to Cloud Run
  - id  : 'Deploy to Cloud Run'
    name: 'google/cloud-sdk'
    args: ['gcloud', 'run', 'deploy', '${_APP_NAME}',
           '--image=${_ZONE_ID}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/${_APP_NAME}:${SHORT_SHA}',
           '--region', '${_ZONE_ID}', '--platform', 'managed',
           '--allow-unauthenticated']

# Store images in Google Artifact Registry
images:
  - ${_ZONE_ID}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/${_APP_NAME}:${SHORT_SHA}

substitutions:
  _ARTIFACT_REGISTRY: emagang-repo
  _ZONE_ID: us-central1
  _APP_NAME: laravel
