steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/${_APP_NAME}:$COMMIT_SHA', '.']
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/${_APP_NAME}:$COMMIT_SHA']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_APP_NAME}'
      - '--image'
      - 'gcr.io/$PROJECT_ID/${_APP_NAME}:$COMMIT_SHA'
      - '--region'
      - 'REGION'
images:
  - 'gcr.io/$PROJECT_ID/${_APP_NAME}:$COMMIT_SHA'


substitutions:
  _APP_NAME: laravel
  _INSTANCE_NAME: emagang-pgsql
  _REGION: us-central1
  _SETTING_NAME: laravel_settings
  _ARTIFACT_REGISTRY: ${_REGION}-docker.pkg.dev/${PROJECT_ID}/emagang-repo
